name: "Docker-Build"
on:
  workflow_dispatch:
  push:
    branches:
     - s1
  pull_request:
    branches:
     - master
     - s1
jobs:
  build:    
    runs-on: 
     - ubuntu-latest
    steps:      
     - name: "Checkout Code"
       uses: actions/checkout@v3
     - name: "Build 1"
       uses: ./
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
