name: "Docker CI/CD"
on:
  workflow_dispatch:
  push:
    branches: [ "s1" ]
  pull_request:
    branches: [ "s1" ]

jobs:
  build-js:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: "npm install modules"
      run: |
        npm install
        npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: .

  test:
    runs-on: ubuntu-latest
    needs: build-js
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/download-artifact@v3
      with:
        name: artifact
    - name: "npm install & test"
      run: | 
        npm install
        npm test
      env:
        CI: true

        #   docker-img:
        # runs-on: ubuntu-latest
        #needs: test
        # name: "docker-build"

